####
#### Copyright 2026 rshadr (rshadr@assembly-cave.tw)
#### See LICENSE for details
####

all: build/report.pdf

build/report.pdf:
	@echo "report.pdf done"

clean:
	rm -rf build

.PHONY: all clean

